# Generated by Django 6.0.3 on 2026-03-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.URLField(blank=True, null=True)),
                ('house', models.CharField(blank=True, max_length=100, null=True)),
                ('actor', models.CharField(blank=True, max_length=150, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='filme',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Filme',
        ),
        migrations.DeleteModel(
            name='Aluguel',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
