# Generated by Django 6.0.3 on 2026-03-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_favorito_remove_aluguel_filme_remove_aluguel_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorito',
            old_name='actor',
            new_name='ator',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='house',
            new_name='casa',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='name',
            new_name='nome',
        ),
    ]
